# Generated by Django 3.2.9 on 2021-11-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20211128_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='total',
            new_name='paid_value',
        ),
    ]
